version: "3.9"

services:
  api:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/local/express/Dockerfile
    volumes:
      - /app.node_modules
      - .:/app
    # ports:
    #   - "1997:1997"
    environment:
      NODE_ENV: ${NODE_ENV}
      FORCE_COLOR: 1
    networks:
      - invoice

  client:
    build:
      context: ./client
      dockerfile: ./docker/local/Dockerfile
    restart: on-failure
    volumes:
        - ./client:/app
        - /app/node_modules
    networks:
        - invoice
  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
        - "8080:80"
    restart: always
    depends_on:
        - api
    volumes:
        - static_volume:/app/staticfiles
        - pdf_volume:/app/docs
    networks:
        - invoice
networks:
  invoice:
    driver : bridge
volumes:
  static_volume:
  pdf_volume: